config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^$', TemplateView.as_view(template_name='gentelella-base.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('tesserae.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^base_portal/', include('tesserae.portal_apps.base_portal.urls', namespace='base_portal')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

tesserae/portal_apps/base_portal/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [
url(r'^participant/new-issue$',
    TemplateView.as_view(template_name='pages/test-datatables.html'), name='new_issue'),
url(r'^participant/my-issues$',
    TemplateView.as_view(template_name='pages/participant/issues/view_issues_list.html'), name='my_issues_list'),
]

tesserae/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

tesserae/portal_apps/admin_portal/models.py
from django.db import models

# Create your models here.

tesserae/portal_apps/base_portal/models.py
from django.db import models

# Create your models here.

tesserae/portal_apps/participant_portal/models.py
from django.db import models

# Create your models here.

tesserae/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

tesserae/portal_apps/admin_portal/views.py
from django.shortcuts import render

# Create your views here.

tesserae/portal_apps/base_portal/views.py
from django.shortcuts import render

# Create your views here.

tesserae/portal_apps/participant_portal/views.py
from django.shortcuts import render

# Create your views here.

tesserae/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

tesserae/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

tesserae/templates/base.html
{% load staticfiles i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}tesserae{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">tesserae</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
 

tesserae/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

tesserae/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

tesserae/templates/gentelella-base.html
<!------------------------------------
--  Theme Installation Instructions --
--
-- $> cd integration/static/
-- $> bower install gentelella --save
-- $> bower install highcharts --save
-- : Open "bower_components/gentelella/build/js/custom.js"
-- : Comment out lines 1843 -> 1863 (try searching for "new PNotify")
-- :    ..these are what cause the "PNotify" example to show up on all pages (annoying!!)
--
-- DEPLOYMENT:
-- $> python manage.py collectstatic
--
-------------------------------------->



<!-- For a full example of this template, check out the author's example page: https://colorlib.com/polygon/gentelella/index.html -->

<!-- Theme downloaded via bower install at: https://github.com/puikinsh/gentelella -->


{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MOSIAC | {% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bower_components/gentelella/vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'bower_components/gentelella/vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'bower_components/gentelella/vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'bower_components/gentelella/vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="{% static 'bower_components/gentelella/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'bower_components/gentelella/vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'bower_components/gentelella/vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">

      <!-- PNotify -->
    <link href="{% static 'bower_components/gentelella/vendors/pnotify/dist/pnotify.css' %}" rel="stylesheet">
    <link href="{% static 'bower_components/gentelella/vendors/pnotify/dist/pnotify.buttons.css' %}" rel="stylesheet">
    <link href="{% static 'bower_components/gentelella/vendors/pnotify/dist/pnotify.nonblock.css' %}" rel="stylesheet">

    <!-- Switchery -->
    <link href="{% static 'bower_components/gentelella/vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'bower_components/gentelella/build/css/custom.min.css' %}" rel="stylesheet">
    <link href="{% static 'tesserae_styles.css' %}" rel="stylesheet">

    {% block head %}{% endblock %}
  {% block top_js %} {% endblock %}
  </head>

  <body class="nav-md footer_fixed">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/" class="site_title"><i class="fa fa-eye"></i> <span>MOSAIC</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
              {% if request.user.is_authenticated %}
            <div class="profile clearfix">

              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{% if request.user.firstname %}{{ request.user.firstname }}{% else %}{{ request.user.username }}{% endif %}</h2>
              </div>
            </div>
              {% endif %}
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
{#                <h3>General</h3>#}
                <ul class="nav side-menu">
                    <li>
                        <a href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a>
                    </li>

                  <li><a><i class="fa fa-envelope-o"></i> Status <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">Compliance</a></li>
                      <li><a href="#">Leave Study</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-edit"></i> Issues <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
{#                      <li><a href="{% url 'new_issue' %}">Report an Issue</a></li>#}
                      <li><a href="{% url 'portal:my_issues_list' %}">My Issues</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-edit"></i> Communications <span class="fa fa-chevron-down"></span></a>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
{#            <div class="sidebar-footer hidden-small">#}
{#              <a data-toggle="tooltip" data-placement="top" title="Settings">#}
{#                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>#}
{#              </a>#}
{#              <a data-toggle="tooltip" data-placement="top" title="FullScreen">#}
{#                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>#}
{#              </a>#}
{#              <a data-toggle="tooltip" data-placement="top" title="Lock">#}
{#                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>#}
{#              </a>#}
{#              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">#}
{#                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>#}
{#              </a>#}
{#            </div>#}
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

                {% if request.user.is_authenticated %}
              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    {% if request.user.firstname %}{{ request.user.firstname }}{% else %}{{ request.user.username }}{% endif %}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a href="#"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>


              </ul>
                    {% else %}
              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    Guest
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="#"> Login</a></li>
                  </ul>
                </li>

              </ul>
                {% endif %}
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        {% block content %}

      {% endblock %}
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'bower_components/gentelella/vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'bower_components/gentelella/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'bower_components/gentelella/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'bower_components/gentelella/vendors/nprogress/nprogress.js' %}"></script>
    <!-- Chart.js -->
    <script src="{% static 'bower_components/gentelella/vendors/Chart.js/dist/Chart.min.js' %}"></script>
    <!-- gauge.js -->
    <script src="{% static 'bower_components/gentelella/vendors/gauge.js/dist/gauge.min.js' %}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{% static 'bower_components/gentelella/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'bower_components/gentelella/vendors/iCheck/icheck.min.js' %}"></script>
    <!-- Skycons -->
    <script src="{% static 'bower_components/gentelella/vendors/skycons/skycons.js' %}"></script>
    <!-- Flot -->
    <script src="{% static 'bower_components/gentelella/vendors/Flot/jquery.flot.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/Flot/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/Flot/jquery.flot.time.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/Flot/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/Flot/jquery.flot.resize.js' %}"></script>
    <!-- Flot plugins -->
    <script src="{% static 'bower_components/gentelella/vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/flot.curvedlines/curvedLines.js' %}"></script>
    <!-- DateJS -->
    <script src="{% static 'bower_components/gentelella/vendors/DateJS/build/date.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'bower_components/gentelella/vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static 'bower_components/gentelella/vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

    <!-- PNotify -->
    <script src="{% static 'bower_components/gentelella/vendors/pnotify/dist/pnotify.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/pnotify/dist/pnotify.buttons.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/pnotify/dist/pnotify.nonblock.js' %}"></script>

    <!-- Switchery -->
    <script src="{% static 'bower_components/gentelella/vendors/switchery/dist/switchery.min.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'bower_components/gentelella/build/js/custom.js' %}"></script>

    {% block js %}{% endblock %}

  </body>
</html>

tesserae/templates/pages/about.html
{% extends "base.html" %}

tesserae/templates/pages/home.html
{% extends "base.html" %}

tesserae/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

tesserae/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

tesserae/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}